stages:
  - build
  - notify

build-job:
  stage: build
  image: debian:bullseye-slim  # Используем более стабильный Debian
  before_script:
    - dpkg --add-architecture i386  # Обязательно для Debian
    - apt-get update && apt-get install -y wget unzip libc6:i386 libstdc++6:i386
    
    # Скачивание Pawn
    - wget https://github.com/pawn-lang/compiler/releases/download/v3.10.10/pawnc-3.10.10-linux.tar.gz
    - tar -xvf pawnc-3.10.10-linux.tar.gz
    
    # Настройка путей (используем полные пути)
    - export PAWN_BIN=$(pwd)/pawnc-3.10.10-linux/bin
    - export PAWN_LIB=$(pwd)/pawnc-3.10.10-linux/lib
    - export PATH=$PATH:$PAWN_BIN
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PAWN_LIB

  script:
    - mkdir -p gamemodes npcmodes plugins scriptfiles
    
    # 1. Запуск реальной компиляции
    # Убедись, что путь к main.pwn и папке pawno/include верный относительно корня репозитория
    - pawncc gamemodes/main.pwn -o"gamemodes/main.amx" -i"pawno/include" -i"gamemodes" "-;+"

  artifacts:
    name: "server_release"
    # Перечисляем только то, что реально нужно на сервере
    paths:
      - "gamemodes/*.amx"
      - "npcmodes/*.amx"
      - "plugins/*.so"
      - "scriptfiles/"
      - "server.cfg"
      - "samp03svr"
      - "*.so"  # Подхватит .so файлы из корня репозитория
    expire_in: 1 day

notify-bot-job:
  stage: notify
  image: curlimages/curl:latest
  script:
    # Замени IP на свой. Бот должен слушать порт 8080 (как мы обсуждали ранее)
    - curl -X POST http://72.62.3.235:6666/webhook/deploy
  dependencies:
    - build-job
  only:
    - test  # Выполнять только при пуше в основную ветку